//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Inputs/HeroKnightInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @HeroKnightInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @HeroKnightInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""HeroKnightInput"",
    ""maps"": [
        {
            ""name"": ""HeroKnight"",
            ""id"": ""e34d3176-250f-46a7-98d0-c6dd1a25e9ad"",
            ""actions"": [
                {
                    ""name"": ""Movimiento"",
                    ""type"": ""Value"",
                    ""id"": ""47cdb613-362e-4ed9-9e60-1ab415ecdf15"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Atacar"",
                    ""type"": ""Button"",
                    ""id"": ""f6df03fa-278b-4258-a630-b344f3f75cf8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Saltar"",
                    ""type"": ""Button"",
                    ""id"": ""9adeca3c-0f8f-4518-9bf7-94a5c452326a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cargar"",
                    ""type"": ""Button"",
                    ""id"": ""010e2bad-eb16-490a-9df4-c69fadfc3acb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""d35baa18-26a5-42f4-8411-b28cacf43faf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Bloquear"",
                    ""type"": ""Button"",
                    ""id"": ""566ad623-9d99-4096-8928-69346d26098d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pausa"",
                    ""type"": ""Button"",
                    ""id"": ""648220aa-f420-4086-9c82-c93bf40d400f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interactuar"",
                    ""type"": ""Button"",
                    ""id"": ""209560ac-1d40-4634-91f5-401eff74ded8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""69188548-30a0-46be-8900-86cb06157761"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Atacar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b66d6f4-51a4-47b5-b0d7-4932ebd3ae08"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Atacar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""2c357e74-f1d1-43b0-853f-7b9f23540d13"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""043f1fc0-1def-4838-8d19-0fe07f520f5d"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b36c302a-635f-42fb-9b2f-f1431bb2b616"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b2a78393-6f7f-42bb-9516-580e59817762"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector Gamepad"",
                    ""id"": ""72ff5f59-a667-4bca-b4fe-e1c87bf9375d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""658dcabb-6867-475e-be80-59365a468dfa"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""619becea-342e-4bfe-ba66-fdc7e142ea0f"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""41d8c5d4-6392-4664-bb3c-5f6869d96167"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""29fe8913-b466-4973-9215-b56e5734e71a"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Saltar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78443c2c-f166-4e20-88e8-9f90a52dda53"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Saltar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e201356-f104-45e4-a82a-631c1d0c03b8"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cargar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02c9c21f-7751-4592-85bd-a00f6f4bdb16"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cargar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f4c3797-6e01-4bec-9fdc-3ee9c0bb545e"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72474565-30b8-44ff-b699-0636923458b8"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62873329-5874-49a1-9e96-0419845b60b8"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bloquear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44b0efff-4e47-48c0-92b5-6f69f8382cb5"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bloquear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4a40aaf-198d-4921-a97a-36912de31baf"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pausa"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26775b37-a449-4e0b-81da-f8a130a6ec83"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pausa"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""347ad900-f6a8-49b7-bbaf-bf432705f6a2"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interactuar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d59eadf4-e8c5-4f1f-b484-5b860622b6eb"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interactuar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""New control scheme"",
            ""bindingGroup"": ""New control scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // HeroKnight
        m_HeroKnight = asset.FindActionMap("HeroKnight", throwIfNotFound: true);
        m_HeroKnight_Movimiento = m_HeroKnight.FindAction("Movimiento", throwIfNotFound: true);
        m_HeroKnight_Atacar = m_HeroKnight.FindAction("Atacar", throwIfNotFound: true);
        m_HeroKnight_Saltar = m_HeroKnight.FindAction("Saltar", throwIfNotFound: true);
        m_HeroKnight_Cargar = m_HeroKnight.FindAction("Cargar", throwIfNotFound: true);
        m_HeroKnight_Dash = m_HeroKnight.FindAction("Dash", throwIfNotFound: true);
        m_HeroKnight_Bloquear = m_HeroKnight.FindAction("Bloquear", throwIfNotFound: true);
        m_HeroKnight_Pausa = m_HeroKnight.FindAction("Pausa", throwIfNotFound: true);
        m_HeroKnight_Interactuar = m_HeroKnight.FindAction("Interactuar", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // HeroKnight
    private readonly InputActionMap m_HeroKnight;
    private IHeroKnightActions m_HeroKnightActionsCallbackInterface;
    private readonly InputAction m_HeroKnight_Movimiento;
    private readonly InputAction m_HeroKnight_Atacar;
    private readonly InputAction m_HeroKnight_Saltar;
    private readonly InputAction m_HeroKnight_Cargar;
    private readonly InputAction m_HeroKnight_Dash;
    private readonly InputAction m_HeroKnight_Bloquear;
    private readonly InputAction m_HeroKnight_Pausa;
    private readonly InputAction m_HeroKnight_Interactuar;
    public struct HeroKnightActions
    {
        private @HeroKnightInput m_Wrapper;
        public HeroKnightActions(@HeroKnightInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movimiento => m_Wrapper.m_HeroKnight_Movimiento;
        public InputAction @Atacar => m_Wrapper.m_HeroKnight_Atacar;
        public InputAction @Saltar => m_Wrapper.m_HeroKnight_Saltar;
        public InputAction @Cargar => m_Wrapper.m_HeroKnight_Cargar;
        public InputAction @Dash => m_Wrapper.m_HeroKnight_Dash;
        public InputAction @Bloquear => m_Wrapper.m_HeroKnight_Bloquear;
        public InputAction @Pausa => m_Wrapper.m_HeroKnight_Pausa;
        public InputAction @Interactuar => m_Wrapper.m_HeroKnight_Interactuar;
        public InputActionMap Get() { return m_Wrapper.m_HeroKnight; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HeroKnightActions set) { return set.Get(); }
        public void SetCallbacks(IHeroKnightActions instance)
        {
            if (m_Wrapper.m_HeroKnightActionsCallbackInterface != null)
            {
                @Movimiento.started -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnMovimiento;
                @Movimiento.performed -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnMovimiento;
                @Movimiento.canceled -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnMovimiento;
                @Atacar.started -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnAtacar;
                @Atacar.performed -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnAtacar;
                @Atacar.canceled -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnAtacar;
                @Saltar.started -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnSaltar;
                @Saltar.performed -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnSaltar;
                @Saltar.canceled -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnSaltar;
                @Cargar.started -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnCargar;
                @Cargar.performed -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnCargar;
                @Cargar.canceled -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnCargar;
                @Dash.started -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnDash;
                @Bloquear.started -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnBloquear;
                @Bloquear.performed -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnBloquear;
                @Bloquear.canceled -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnBloquear;
                @Pausa.started -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnPausa;
                @Pausa.performed -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnPausa;
                @Pausa.canceled -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnPausa;
                @Interactuar.started -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnInteractuar;
                @Interactuar.performed -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnInteractuar;
                @Interactuar.canceled -= m_Wrapper.m_HeroKnightActionsCallbackInterface.OnInteractuar;
            }
            m_Wrapper.m_HeroKnightActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movimiento.started += instance.OnMovimiento;
                @Movimiento.performed += instance.OnMovimiento;
                @Movimiento.canceled += instance.OnMovimiento;
                @Atacar.started += instance.OnAtacar;
                @Atacar.performed += instance.OnAtacar;
                @Atacar.canceled += instance.OnAtacar;
                @Saltar.started += instance.OnSaltar;
                @Saltar.performed += instance.OnSaltar;
                @Saltar.canceled += instance.OnSaltar;
                @Cargar.started += instance.OnCargar;
                @Cargar.performed += instance.OnCargar;
                @Cargar.canceled += instance.OnCargar;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @Bloquear.started += instance.OnBloquear;
                @Bloquear.performed += instance.OnBloquear;
                @Bloquear.canceled += instance.OnBloquear;
                @Pausa.started += instance.OnPausa;
                @Pausa.performed += instance.OnPausa;
                @Pausa.canceled += instance.OnPausa;
                @Interactuar.started += instance.OnInteractuar;
                @Interactuar.performed += instance.OnInteractuar;
                @Interactuar.canceled += instance.OnInteractuar;
            }
        }
    }
    public HeroKnightActions @HeroKnight => new HeroKnightActions(this);
    private int m_NewcontrolschemeSchemeIndex = -1;
    public InputControlScheme NewcontrolschemeScheme
    {
        get
        {
            if (m_NewcontrolschemeSchemeIndex == -1) m_NewcontrolschemeSchemeIndex = asset.FindControlSchemeIndex("New control scheme");
            return asset.controlSchemes[m_NewcontrolschemeSchemeIndex];
        }
    }
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IHeroKnightActions
    {
        void OnMovimiento(InputAction.CallbackContext context);
        void OnAtacar(InputAction.CallbackContext context);
        void OnSaltar(InputAction.CallbackContext context);
        void OnCargar(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnBloquear(InputAction.CallbackContext context);
        void OnPausa(InputAction.CallbackContext context);
        void OnInteractuar(InputAction.CallbackContext context);
    }
}
